spring:
  application:
    name: zeebot
  
  main:
    web-application-type: none

  ai:
    openai:
      api-key: "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"
      chat:
        options:
          model: "gpt-4o-mini"



pinecone:
  api-key: pcsk_66BKVG_8m6CKuTYMTbqJxtLMCDX6WU4JMLDtWWQ5swLmKxABjZB1qUZCYzGoqLFCdZKfpK
  index-host: https://zeebot-index-xbbxo6w.svc.aped-4627-b74a.pinecone.io
  namespace: zeebot-files

